---
# Source: weave-scope/charts/weave-scope-cluster-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:    
    chart: weave-scope-cluster-agent-1.1.10
    heritage: Helm
    release: scope
    app: weave-scope
    component: agent
  name: weave-scope-cluster-agent-scope
  annotations:    
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4fe8efe",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml"
        },
        "email-address": "support@weave.works",
        "source-app": "weave-scope",
        "weave-cloud-component": "scope"
      }
---
# Source: weave-scope/templates/test-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: weave-scope-scope-tests
  labels:    
    chart: weave-scope-1.1.10
    heritage: Helm
    release: scope
    app: weave-scope
data:
  run.sh: |-

    @test "Testing Weave Scope UI is accessible" {
      curl --retry 12 --retry-delay 10 http://scope-weave-scope.weave.svc:80
    }
---
# Source: weave-scope/charts/weave-scope-cluster-agent/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:    
    chart: weave-scope-cluster-agent-1.1.10
    heritage: Helm
    release: scope
    app: weave-scope
    component: agent
  name: weave-scope-cluster-agent-scope 
  annotations:    
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4fe8efe",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml"
        },
        "email-address": "support@weave.works",
        "source-app": "weave-scope",
        "weave-cloud-component": "scope"
      }
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
# Source: weave-scope/charts/weave-scope-cluster-agent/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:    
    chart: weave-scope-cluster-agent-1.1.10
    heritage: Helm
    release: scope
    app: weave-scope
    component: agent
  name: scope-weave-scope
  annotations:    
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4fe8efe",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml"
        },
        "email-address": "support@weave.works",
        "source-app": "weave-scope",
        "weave-cloud-component": "scope"
      }
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weave-scope-cluster-agent-scope
subjects:
  - kind: ServiceAccount
    name: weave-scope-cluster-agent-scope
    namespace: weave
---
# Source: weave-scope/charts/weave-scope-frontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:    
    chart: weave-scope-frontend-1.1.10
    heritage: Helm
    release: scope
    app: weave-scope
    component: frontend
  name: scope-weave-scope
  annotations:    
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4fe8efe",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml"
        },
        "email-address": "support@weave.works",
        "source-app": "weave-scope",
        "weave-cloud-component": "scope"
      }
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: weave-scope
    release: scope
    component: frontend
  type: ClusterIP
---
# Source: weave-scope/charts/weave-scope-agent/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:    
    chart: weave-scope-agent-1.1.10
    heritage: Helm
    release: scope
    app: weave-scope
    component: agent
  name: weave-scope-agent-scope
  annotations:    
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4fe8efe",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml"
        },
        "email-address": "support@weave.works",
        "source-app": "weave-scope",
        "weave-cloud-component": "scope"
      }
spec:
  selector:
    matchLabels:
      app: weave-scope
      release: scope
      component: agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:        
        chart: weave-scope-agent-1.1.10
        heritage: Helm
        release: scope
        app: weave-scope
        component: agent
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: weave-scope-agent
          image: "weaveworks/scope:1.12.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - '--mode=probe'
            - '--probe-only'
            - '--probe.kubernetes.role=host'
            - '--probe.docker.bridge=docker0'
            - '--probe.docker=true'
            - '--probe.kubernetes=true'
            
            - scope-weave-scope.weave.svc:80
          securityContext:
            privileged: true
          resources:
            null
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: scope-plugins
              mountPath: /var/run/scope/plugins
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: scope-plugins
          hostPath:
            path: /var/run/scope/plugins
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
---
# Source: weave-scope/charts/weave-scope-cluster-agent/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:    
    chart: weave-scope-cluster-agent-1.1.10
    heritage: Helm
    release: scope
    app: weave-scope
    component: cluster-agent
  name: weave-scope-cluster-agent-scope
  annotations:    
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4fe8efe",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml"
        },
        "email-address": "support@weave.works",
        "source-app": "weave-scope",
        "weave-cloud-component": "scope"
      }
spec:
  selector:
    matchLabels:
      app: weave-scope
      release: scope
      component: cluster-agent
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:        
        chart: weave-scope-cluster-agent-1.1.10
        heritage: Helm
        release: scope
        app: weave-scope
        component: cluster-agent
    spec:
      containers:
        - name: weave-scope-cluster-agent
          image: "weaveworks/scope:1.12.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - '--mode=probe'
            - '--probe-only'
            - '--probe.kubernetes.role=cluster'
            
            - scope-weave-scope.weave.svc:80
          resources:
            null
      serviceAccountName: weave-scope-cluster-agent-scope
---
# Source: weave-scope/charts/weave-scope-frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:    
    chart: weave-scope-frontend-1.1.10
    heritage: Helm
    release: scope
    app: weave-scope
    component: frontend
  name: weave-scope-frontend-scope
  annotations:    
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4fe8efe",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml"
        },
        "email-address": "support@weave.works",
        "source-app": "weave-scope",
        "weave-cloud-component": "scope"
      }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weave-scope
      release: scope
      component: frontend
  template:
    metadata:
      labels:        
        chart: weave-scope-frontend-1.1.10
        heritage: Helm
        release: scope
        app: weave-scope
        component: frontend
    spec:
      containers:
        - name: weave-scope-frontend
          image: "weaveworks/scope:1.12.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - "--no-probe"
          ports:
            - name: http
              containerPort: 4040
              protocol: TCP
          resources:
            null
---
# Source: weave-scope/templates/weave-scope-tests.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "scope-ui-test-mtcw9"
  annotations:
    "helm.sh/hook": test-success
  labels:    
    chart: weave-scope-1.1.10
    heritage: Helm
    release: scope
    app: weave-scope
spec:
  initContainers:
    - name: "test-framework"
      image: "dduportal/bats:0.4.0"
      command:
      - "bash"
      - "-c"
      - |
        set -ex
        # copy bats to tools dir
        cp -R /usr/local/libexec/ /tools/bats/
      volumeMounts:
      - mountPath: /tools
        name: tools
  containers:
    - name: scope-ui-test
      image: dduportal/bats:0.4.0
      command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
      volumeMounts:
      - mountPath: /tests
        name: tests
        readOnly: true
      - mountPath: /tools
        name: tools
  volumes:
  - name: tests
    configMap:
      name: weave-scope-scope-tests
  - name: tools
    emptyDir: {}
  restartPolicy: Never
