---
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: weave-ingress
      annotations:
        ingress.kubernetes.io/rewrite-target: /
    spec:
      tls:
      - hosts:
        - weave.test-test.com
      rules:
      - host: weave.test-test.com
        http:
          paths:
          - path: /
            backend:
              serviceName: scope-weave-scope
              servicePort: 80