apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/istio/dev
    repoURL: https://gitub.com/vhsanche/kube
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true