apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weave
  namespace: dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/postgresql/dev
    repoURL: https://github.com/vhsanche/kube.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true